version: '2.1'

services:

  metagenscope-db:
    container_name: metagenscope-db
    build: ./app/db
    ports:
      - 5435:5432  # expose ports - HOST:CONTAINER
    environment:
      # These are not used in production so it is fine to commit them
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: exit 0

  metagenscope-service:
    container_name: metagenscope-service
    build: .
    volumes:
      - '.:/usr/src/app'
    ports:
      - 5001:5000 # expose ports - HOST:CONTAINER
    environment:
      # Environment: development | testing | staging | production
      - APP_SETTINGS=development
      - SECRET_KEY=my_precious
      - DATABASE_URL=postgres://postgres:postgres@metagenscope-db:5432/users_dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@metagenscope-db:5432/users_test
    depends_on:
      metagenscope-db:
        condition: service_healthy
    links:
      - metagenscope-db
